# Generated by Django 4.0.1 on 2022-01-29 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sudent_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mobile_number',
        ),
    ]
